# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 13:06
from __future__ import unicode_literals

import ananta.models
import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0015_auto_20160630_1131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('first_name', models.CharField(blank=True, help_text='Enter your first name.', max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Enter your middle name.', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Enter your surname.', max_length=100)),
                ('initiated_name', models.CharField(blank=True, help_text='Spiritual name if you have e.g: Krishna Das, Tulasi Dasi, Bhakta Burfi', max_length=100)),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Enter your phone number. If it is a non-Indian number please use the international format e.g.: +421 222 333 444', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('INR', '₹ (INR)'), ('USD', '$ (USD)'), ('EUR', '€ (EUR)'), ('GBP', '£ (GBP)'), ('CAD', 'C$ (CAD)'), ('RUB', '₽ (RUB)')], default='INR', max_length=6, verbose_name='Currency')),
                ('number_of_instalments', models.IntegerField(default=1, verbose_name='Number of instalments')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_donate_webdonation_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_donate_webdonation_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_donations', to='contacts.Person', verbose_name='Person')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, ananta.models.NextPrevMixin),
        ),
    ]
