# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdonation',
            name='csrf_token',
            field=models.CharField(blank=True, help_text='CSRF Token is used to identify re-submit records.', max_length=100),
        ),
    ]
