language: python
python:
  - "3.4"
env:
  global:
    - DATABASE_URL="postgres://postgres@localhost/tovp"
    - DJANGO_CONFIGURATION=Travis
  matrix:
    - DJANGO=1.7.1
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements/test.txt
before_script:
  - psql -c 'create database tovp;' -U postgres
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
  - flake8 --ignore=E501 tovp
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
script:
  - cd tovp;python manage.py test
  - cd tovp;coverage run --source=. manage.py test
