language: python
python:
  - "3.4"
env:
  global:
    - DATABASE_URL="postgres://postgres@localhost/tovp"
    - DJANGO_CONFIGURATION=Travis
  matrix:
    - DJANGO=1.7.1
# command to install dependencies
before_script:
  - psql -c 'create database tovp;' -U postgres
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
script: coverage run --source=tovp manage.py test
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements/test.txt
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
# command to run tests
script: python manage.py test
