# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_auto_20150615_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaldonation',
            options={'verbose_name': 'General Donation'},
        ),
        migrations.AlterModelOptions(
            name='goldenbrick',
            options={'verbose_name': 'Golden Brick'},
        ),
        migrations.AlterModelOptions(
            name='nrsimhatile',
            options={'verbose_name': 'Nrsimha Tile'},
        ),
        migrations.AlterModelOptions(
            name='radhamadhavabrick',
            options={'verbose_name': 'Radha Madhava Brick'},
        ),
    ]
