# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_auto_20161010_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenbrick',
            name='brick_status',
            field=models.CharField(choices=[('need_to_send', 'Need to produce'), ('name_given', 'In production'), ('brick_made', 'Finished')], default='need_to_send', max_length=100, verbose_name='Brick Status'),
        ),
        migrations.AlterField(
            model_name='guruparamparabrick',
            name='brick_status',
            field=models.CharField(choices=[('need_to_send', 'Need to produce'), ('name_given', 'In production'), ('brick_made', 'Finished')], default='need_to_send', max_length=100, verbose_name='Brick Status'),
        ),
        migrations.AlterField(
            model_name='nrsimhatile',
            name='brick_status',
            field=models.CharField(choices=[('need_to_send', 'Need to produce'), ('name_given', 'In production'), ('brick_made', 'Finished')], default='need_to_send', max_length=100, verbose_name='Brick Status'),
        ),
        migrations.AlterField(
            model_name='radhamadhavabrick',
            name='brick_status',
            field=models.CharField(choices=[('need_to_send', 'Need to produce'), ('name_given', 'In production'), ('brick_made', 'Finished')], default='need_to_send', max_length=100, verbose_name='Brick Status'),
        ),
    ]
