# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0058_auto_20161010_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpayment',
            name='source',
            field=models.CharField(blank=True, choices=[('tovp-f-mayapur', 'TOVP Fundraising Mayapur'), ('tovp-exhibits', 'TOVP Exhibits'), ('bcs-vp-2015', 'BCS Vyasa Puja 2015'), ('bhagavata-saptaha-2015', 'Bhagavata Saptaha 2015'), ('bhakti-vriksa-kolkata-2016', 'Bhakti Vriksa Kolkata 2016'), ('braj-mohan-mumbai', 'Braj Mohan (Mumbai)'), ('delhi-vidyanagar-2015', 'Delhi Vidyanagar 2015'), ('gkg-vp-2015', 'GKG Vyasa Puja 2015'), ('gkg-vp-2016', 'GKG Vyasa Puja 2016'), ('ils-2016', 'ILS 2016'), ('iskcon-silicon-valley', 'ISKCON Silicon Valley (ISV)'), ('j-w-marriot', 'J W Marriot'), ('jps-office', 'JPS Office'), ('jps-others', 'JPS Others'), ('kanjurmarg-mumbai-2015', 'Kanjurmarg Mumbai 2015'), ('lm-reception', 'Life Membership Reception'), ('mayapur-community', 'Mayapur Community'), ('mso', 'MSO'), ('mumbai-yatra-2016', 'Mumbai Yatra 2016'), ('namahatta', 'JPS Namahatta'), ('botswana-2016', 'Botswana 2016'), ('south-afrika-2016', 'South Afrika 2016'), ('neel-vasan-das', 'Neel Vasan Das'), ('nigdi-2016.', 'Nigdi 2016.'), ('nityananda', 'Nityananda Tour'), ('nvs', 'Nava Yogendra Swami'), ('other', 'Other'), ('prabhupada-currency-inr', 'Prabhupada Currency INR'), ('pune-group-mayapur-2015', 'Pune Group Mayapur 2015'), ('pune-yatra-2016', 'Pune Yatra 2016'), ('rns-kartik-yatra', 'RNS Kartik Yatra'), ('rohini-narayani', 'Rohini (Sri Narayani Devi Dasi)'), ('vrindavan-booth', 'Vrindavan Booth 2015'), ('vrindavan-booth-2016', 'Vrindavan Booth 2016'), ('vvps-vp-2015', 'Vedavyasapriya Swami Vyasa Puja 2015')], default='', max_length=30, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='source',
            field=models.CharField(blank=True, choices=[('tovp-f-mayapur', 'TOVP Fundraising Mayapur'), ('tovp-exhibits', 'TOVP Exhibits'), ('bcs-vp-2015', 'BCS Vyasa Puja 2015'), ('bhagavata-saptaha-2015', 'Bhagavata Saptaha 2015'), ('bhakti-vriksa-kolkata-2016', 'Bhakti Vriksa Kolkata 2016'), ('braj-mohan-mumbai', 'Braj Mohan (Mumbai)'), ('delhi-vidyanagar-2015', 'Delhi Vidyanagar 2015'), ('gkg-vp-2015', 'GKG Vyasa Puja 2015'), ('gkg-vp-2016', 'GKG Vyasa Puja 2016'), ('ils-2016', 'ILS 2016'), ('iskcon-silicon-valley', 'ISKCON Silicon Valley (ISV)'), ('j-w-marriot', 'J W Marriot'), ('jps-office', 'JPS Office'), ('jps-others', 'JPS Others'), ('kanjurmarg-mumbai-2015', 'Kanjurmarg Mumbai 2015'), ('lm-reception', 'Life Membership Reception'), ('mayapur-community', 'Mayapur Community'), ('mso', 'MSO'), ('mumbai-yatra-2016', 'Mumbai Yatra 2016'), ('namahatta', 'JPS Namahatta'), ('botswana-2016', 'Botswana 2016'), ('south-afrika-2016', 'South Afrika 2016'), ('neel-vasan-das', 'Neel Vasan Das'), ('nigdi-2016.', 'Nigdi 2016.'), ('nityananda', 'Nityananda Tour'), ('nvs', 'Nava Yogendra Swami'), ('other', 'Other'), ('prabhupada-currency-inr', 'Prabhupada Currency INR'), ('pune-group-mayapur-2015', 'Pune Group Mayapur 2015'), ('pune-yatra-2016', 'Pune Yatra 2016'), ('rns-kartik-yatra', 'RNS Kartik Yatra'), ('rohini-narayani', 'Rohini (Sri Narayani Devi Dasi)'), ('vrindavan-booth', 'Vrindavan Booth 2015'), ('vrindavan-booth-2016', 'Vrindavan Booth 2016'), ('vvps-vp-2015', 'Vedavyasapriya Swami Vyasa Puja 2015')], default='', max_length=30, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='source',
            field=models.CharField(blank=True, choices=[('tovp-f-mayapur', 'TOVP Fundraising Mayapur'), ('tovp-exhibits', 'TOVP Exhibits'), ('bcs-vp-2015', 'BCS Vyasa Puja 2015'), ('bhagavata-saptaha-2015', 'Bhagavata Saptaha 2015'), ('bhakti-vriksa-kolkata-2016', 'Bhakti Vriksa Kolkata 2016'), ('braj-mohan-mumbai', 'Braj Mohan (Mumbai)'), ('delhi-vidyanagar-2015', 'Delhi Vidyanagar 2015'), ('gkg-vp-2015', 'GKG Vyasa Puja 2015'), ('gkg-vp-2016', 'GKG Vyasa Puja 2016'), ('ils-2016', 'ILS 2016'), ('iskcon-silicon-valley', 'ISKCON Silicon Valley (ISV)'), ('j-w-marriot', 'J W Marriot'), ('jps-office', 'JPS Office'), ('jps-others', 'JPS Others'), ('kanjurmarg-mumbai-2015', 'Kanjurmarg Mumbai 2015'), ('lm-reception', 'Life Membership Reception'), ('mayapur-community', 'Mayapur Community'), ('mso', 'MSO'), ('mumbai-yatra-2016', 'Mumbai Yatra 2016'), ('namahatta', 'JPS Namahatta'), ('botswana-2016', 'Botswana 2016'), ('south-afrika-2016', 'South Afrika 2016'), ('neel-vasan-das', 'Neel Vasan Das'), ('nigdi-2016.', 'Nigdi 2016.'), ('nityananda', 'Nityananda Tour'), ('nvs', 'Nava Yogendra Swami'), ('other', 'Other'), ('prabhupada-currency-inr', 'Prabhupada Currency INR'), ('pune-group-mayapur-2015', 'Pune Group Mayapur 2015'), ('pune-yatra-2016', 'Pune Yatra 2016'), ('rns-kartik-yatra', 'RNS Kartik Yatra'), ('rohini-narayani', 'Rohini (Sri Narayani Devi Dasi)'), ('vrindavan-booth', 'Vrindavan Booth 2015'), ('vrindavan-booth-2016', 'Vrindavan Booth 2016'), ('vvps-vp-2015', 'Vedavyasapriya Swami Vyasa Puja 2015')], default='', max_length=30, verbose_name='Source'),
        ),
    ]
