# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0061_auto_20170301_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkpayment',
            old_name='source',
            new_name='source_old',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='source',
            new_name='source_old',
        ),
        migrations.RenameField(
            model_name='pledge',
            old_name='source',
            new_name='source_old',
        ),
    ]
