# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0063_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bulkpayment',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.Source', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.Source', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.Source', verbose_name='Source'),
        ),
    ]
